# imports

In [1]:
from pathlib import Path
from typing import Optional, Any, Union

import numpy as np
import polars as pl

# plotting
import matplotlib.pyplot as plt
import plotly.express as px
from dash import Dash, dcc, html, Input, Output, State, callback_context
import plotly.graph_objects as go

# scipy
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
from sklearn.cluster import KMeans

# muutils
import muutils.tensor_info
from muutils.dbg import dbg, dbg_tensor

# attention-motifs
from attention_motifs.features.analysis import nan_stats, filter_data, normalize_data
from attention_motifs.features.plotting import (
	plot_correlation_matrix,
	plot_embedding,
	apply_pca,
)

muutils.tensor_info.DEFAULT_SETTINGS["colored"] = True

from pathlib import Path
from typing import Optional, Any, Union

import numpy as np
from jaxtyping import Float

import polars as pl

# muutils
from muutils.jsonlines import jsonl_write, jsonl_load

# attention-motifs
from attention_motifs.bins import Bins
from attention_motifs.features.features import scalar_feature_table
from attention_motifs.features.hist_beta_fit import hist_beta_fit
from attention_motifs.util import prefix_dict
from attention_motifs.features.transition_tensor import tt_features
from attention_motifs.features.vec_features import vec_features
from attention_motifs.math.cos_sim import cosine_similarity_matrix
from attention_motifs.math.math import skew_lt
from attention_motifs.features.analysis import nan_stats, filter_data, normalize_data

# set up feature generation

In [2]:
def gram_features(A: Float[np.ndarray, "n_ctx n_ctx"]) -> dict[str, float]:
	# dbg_tensor(A)
	return prefix_dict(
		hist_beta_fit(
			A.flatten(),
			bins=Bins(n_bins=32, start=0.0, stop=1.0),
		),
		prefix="beta_hist",
	)
	# TODO: mass as a function of distance from diagonal

In [3]:
def compute_scalar_features(
	A: Float[np.ndarray, "n_ctx n_ctx"],
) -> dict[str, float]:
	# dbg_tensor(A)
	A_log: Float[np.ndarray, "n_ctx n_ctx"] = np.nan_to_num(np.log(A + 1e-9), nan=-10)
	# dbg_tensor(A_log)

	A_skew: Float[np.ndarray, "n_ctx n_ctx"] = skew_lt(A)
	# dbg_tensor(A_skew)
	A_log_skew: Float[np.ndarray, "n_ctx n_ctx"] = skew_lt(A_log)

	return dict(
		# diagonal: standard features, fit diff to beta dist
		**prefix_dict(vec_features(A.diagonal()), prefix="diag"),
		# off-diagonal: standard features, fit diff to beta dist
		**prefix_dict(vec_features(A[:, 0]), prefix="first_tok"),
		# transition tensor: standard features, standard features on diff, linear envelope on transition time
		# 	TODO: standard features on decay rate
		**prefix_dict(
			tt_features(A),
			prefix="markov_transition",
		),
		# # {log, raw} gram matrix of {rows, cols, rows of skewed}: beta fit hist
		# # 	TODO: fit fft in `gram_features`, but this is expensive
		**prefix_dict(
			gram_features(A @ A.T),
			prefix=["gram", "row"],
		),
		**prefix_dict(
			gram_features(A.T @ A),
			prefix=["gram", "col"],
		),
		**prefix_dict(
			gram_features(A_skew.T @ A_skew),
			prefix=["gram", "skew"],
		),
		**prefix_dict(
			gram_features(cosine_similarity_matrix(A_log)),
			prefix=["log", "gram", "row"],
		),
		**prefix_dict(
			gram_features(cosine_similarity_matrix(A_log, col=True)),
			prefix=["log", "gram", "col"],
		),
		**prefix_dict(
			gram_features(cosine_similarity_matrix(A_log_skew)),
			prefix=["log", "gram", "skew"],
		),
	)

# run feature gen

In [4]:
DATA_RAW: pl.DataFrame = scalar_feature_table(
	features_func=compute_scalar_features,
	models=["pythia-14m", "tiny-stories-1M"],
)

models: ['pythia-14m', 'tiny-stories-1M']
model: 'pythia-14m'
✔️  (0.00s) setting up paths
✔️  (0.01s) loading prompts
128 prompts loaded

100%|██████████| 128/128 [01:02<00:00,  2.06it/s]

model: 'tiny-stories-1M'
✔️  (0.00s) setting up paths
✔️  (0.00s) loading prompts
128 prompts loaded

100%|██████████| 128/128 [05:56<00:00,  2.79s/it]

# save raw data

In [43]:
DATA_RAW.write_ndjson(Path("../data/features/raw.jsonl"))

# basic data inspection

In [44]:
DATA_RAW

shape: (19_456, 183)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ activatio ┆ activatio ┆ activatio ┆ activatio ┆ … ┆ feat.log. ┆ feat.log. ┆ feat.log. ┆ feat.log │
│ n.model   ┆ n.layer   ┆ n.cache_k ┆ n.head    ┆   ┆ gram.skew ┆ gram.skew ┆ gram.skew ┆ .gram.sk │
│ ---       ┆ ---       ┆ ey        ┆ ---       ┆   ┆ .beta_his ┆ .beta_his ┆ .beta_his ┆ ew.beta_ │
│ str       ┆ i64       ┆ ---       ┆ i64       ┆   ┆ t.h…      ┆ t.h…      ┆ t.h…      ┆ hist.h…  │
│           ┆           ┆ str       ┆           ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ pythia-14 ┆ 0         ┆ blocks.0. ┆ 0         ┆ … ┆ 16.549212 ┆ -0.055552 ┆ 1.792928  ┆ 0.029031 │
│ m         ┆           ┆ attn.hook ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ _pattern  ┆           ┆   ┆           ┆           ┆           ┆          │
│ pythia-14 ┆ 0         ┆ blocks.0. ┆ 1         ┆ … ┆ 14.921705 ┆ -0.06731  ┆ 2.131102  ┆ 0.043626 │
│ m         ┆           ┆ attn.hook ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ _pattern  ┆           ┆   ┆           ┆           ┆           ┆          │
│ pythia-14 ┆ 0         ┆ blocks.0. ┆ 2         ┆ … ┆ 18.22198  ┆ -0.058307 ┆ 1.765544  ┆ 0.031686 │
│ m         ┆           ┆ attn.hook ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ _pattern  ┆           ┆   ┆           ┆           ┆           ┆          │
│ pythia-14 ┆ 0         ┆ blocks.0. ┆ 3         ┆ … ┆ 15.016021 ┆ -0.05619  ┆ 1.820761  ┆ 0.029747 │
│ m         ┆           ┆ attn.hook ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ _pattern  ┆           ┆   ┆           ┆           ┆           ┆          │
│ pythia-14 ┆ 1         ┆ blocks.1. ┆ 0         ┆ … ┆ 8.932156  ┆ -0.078382 ┆ 2.461131  ┆ 0.060452 │
│ m         ┆           ┆ attn.hook ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ _pattern  ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ tiny-stor ┆ 7         ┆ blocks.7. ┆ 11        ┆ … ┆ 31.939634 ┆ -0.102208 ┆ 2.648298  ┆ 0.047851 │
│ ies-1M    ┆           ┆ attn.hook ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ _pattern  ┆           ┆   ┆           ┆           ┆           ┆          │
│ tiny-stor ┆ 7         ┆ blocks.7. ┆ 12        ┆ … ┆ 31.627462 ┆ -0.102604 ┆ 2.651247  ┆ 0.04818  │
│ ies-1M    ┆           ┆ attn.hook ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ _pattern  ┆           ┆   ┆           ┆           ┆           ┆          │
│ tiny-stor ┆ 7         ┆ blocks.7. ┆ 13        ┆ … ┆ 31.171712 ┆ -0.101023 ┆ 2.660252  ┆ 0.04674  │
│ ies-1M    ┆           ┆ attn.hook ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ _pattern  ┆           ┆   ┆           ┆           ┆           ┆          │
│ tiny-stor ┆ 7         ┆ blocks.7. ┆ 14        ┆ … ┆ 31.958574 ┆ -0.103813 ┆ 2.648708  ┆ 0.049263 │
│ ies-1M    ┆           ┆ attn.hook ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ _pattern  ┆           ┆   ┆           ┆           ┆           ┆          │
│ tiny-stor ┆ 7         ┆ blocks.7. ┆ 15        ┆ … ┆ 31.475969 ┆ -0.103952 ┆ 2.653133  ┆ 0.049379 │
│ ies-1M    ┆           ┆ attn.hook ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ _pattern  ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [45]:
set(DATA_RAW.dtypes)

{Float64, Int64, String}

In [46]:
DATA_RAW.head()

shape: (5, 183)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ activatio ┆ activatio ┆ activatio ┆ activatio ┆ … ┆ feat.log. ┆ feat.log. ┆ feat.log. ┆ feat.log │
│ n.model   ┆ n.layer   ┆ n.cache_k ┆ n.head    ┆   ┆ gram.skew ┆ gram.skew ┆ gram.skew ┆ .gram.sk │
│ ---       ┆ ---       ┆ ey        ┆ ---       ┆   ┆ .beta_his ┆ .beta_his ┆ .beta_his ┆ ew.beta_ │
│ str       ┆ i64       ┆ ---       ┆ i64       ┆   ┆ t.h…      ┆ t.h…      ┆ t.h…      ┆ hist.h…  │
│           ┆           ┆ str       ┆           ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ pythia-14 ┆ 0         ┆ blocks.0. ┆ 0         ┆ … ┆ 16.549212 ┆ -0.055552 ┆ 1.792928  ┆ 0.029031 │
│ m         ┆           ┆ attn.hook ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ _pattern  ┆           ┆   ┆           ┆           ┆           ┆          │
│ pythia-14 ┆ 0         ┆ blocks.0. ┆ 1         ┆ … ┆ 14.921705 ┆ -0.06731  ┆ 2.131102  ┆ 0.043626 │
│ m         ┆           ┆ attn.hook ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ _pattern  ┆           ┆   ┆           ┆           ┆           ┆          │
│ pythia-14 ┆ 0         ┆ blocks.0. ┆ 2         ┆ … ┆ 18.22198  ┆ -0.058307 ┆ 1.765544  ┆ 0.031686 │
│ m         ┆           ┆ attn.hook ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ _pattern  ┆           ┆   ┆           ┆           ┆           ┆          │
│ pythia-14 ┆ 0         ┆ blocks.0. ┆ 3         ┆ … ┆ 15.016021 ┆ -0.05619  ┆ 1.820761  ┆ 0.029747 │
│ m         ┆           ┆ attn.hook ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ _pattern  ┆           ┆   ┆           ┆           ┆           ┆          │
│ pythia-14 ┆ 1         ┆ blocks.1. ┆ 0         ┆ … ┆ 8.932156  ┆ -0.078382 ┆ 2.461131  ┆ 0.060452 │
│ m         ┆           ┆ attn.hook ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ _pattern  ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [47]:
DATA_RAW.describe()

shape: (9, 184)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ activatio ┆ activatio ┆ activatio ┆ … ┆ feat.log. ┆ feat.log. ┆ feat.log. ┆ feat.log │
│ ---       ┆ n.model   ┆ n.layer   ┆ n.cache_k ┆   ┆ gram.skew ┆ gram.skew ┆ gram.skew ┆ .gram.sk │
│ str       ┆ ---       ┆ ---       ┆ ey        ┆   ┆ .beta_his ┆ .beta_his ┆ .beta_his ┆ ew.beta_ │
│           ┆ str       ┆ f64       ┆ ---       ┆   ┆ t.h…      ┆ t.h…      ┆ t.h…      ┆ hist.h…  │
│           ┆           ┆           ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 19456     ┆ 19456.0   ┆ 19456     ┆ … ┆ 19456.0   ┆ 19456.0   ┆ 19456.0   ┆ 19456.0  │
│ null_coun ┆ 0         ┆ 0.0       ┆ 0         ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ null      ┆ 3.342105  ┆ null      ┆ … ┆ 24.899773 ┆ -0.076354 ┆ 2.20839   ┆ 0.035693 │
│ std       ┆ null      ┆ 2.239375  ┆ null      ┆ … ┆ 24.313324 ┆ 0.057907  ┆ 1.204615  ┆ 0.017003 │
│ min       ┆ pythia-14 ┆ 0.0       ┆ blocks.0. ┆ … ┆ 1.26029   ┆ -0.454373 ┆ 0.483393  ┆ 8.8602e- │
│           ┆ m         ┆           ┆ attn.hook ┆   ┆           ┆           ┆           ┆ 9        │
│           ┆           ┆           ┆ _pattern  ┆   ┆           ┆           ┆           ┆          │
│ 25%       ┆ null      ┆ 1.0       ┆ null      ┆ … ┆ 14.537574 ┆ -0.080022 ┆ 1.640449  ┆ 0.027344 │
│ 50%       ┆ null      ┆ 3.0       ┆ null      ┆ … ┆ 18.597437 ┆ -0.061878 ┆ 1.881671  ┆ 0.0338   │
│ 75%       ┆ null      ┆ 5.0       ┆ null      ┆ … ┆ 23.834102 ┆ -0.050664 ┆ 2.288446  ┆ 0.041902 │
│ max       ┆ tiny-stor ┆ 7.0       ┆ blocks.7. ┆ … ┆ 271.15075 ┆ 0.010628  ┆ 10.150386 ┆ 0.181303 │
│           ┆ ies-1M    ┆           ┆ attn.hook ┆   ┆ 3         ┆           ┆           ┆          │
│           ┆           ┆           ┆ _pattern  ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [48]:
# print unique values for columns which start with "activations"
print(f"{DATA_RAW['activation.model'].unique() = }")

DATA_RAW['activation.model'].unique() = shape: (2,)
Series: 'activation.model' [str]
[
	"tiny-stories-1M"
	"pythia-14m"
]

In [49]:
for col in DATA_RAW.columns:
	if col.startswith("activation"):
		print(f"{col = }")

col = 'activation.model'
col = 'activation.layer'
col = 'activation.cache_key'
col = 'activation.head'
col = 'activation.cls'
col = 'activation.prompt'
col = 'activation.n_ctx'

In [56]:
nan_stats_df = nan_stats(DATA_RAW)
print(set(nan_stats_df["count"]))
nan_stats_df

{0}

shape: (183, 2)
┌─────────────────────────────────┬───────┐
│ feature                         ┆ count │
│ ---                             ┆ ---   │
│ str                             ┆ u32   │
╞═════════════════════════════════╪═══════╡
│ activation.model                ┆ 0     │
│ activation.layer                ┆ 0     │
│ activation.cache_key            ┆ 0     │
│ activation.head                 ┆ 0     │
│ activation.cls                  ┆ 0     │
│ …                               ┆ …     │
│ feat.log.gram.skew.beta_hist.h… ┆ 0     │
│ feat.log.gram.skew.beta_hist.h… ┆ 0     │
│ feat.log.gram.skew.beta_hist.h… ┆ 0     │
│ feat.log.gram.skew.beta_hist.h… ┆ 0     │
│ feat.log.gram.skew.beta_hist.h… ┆ 0     │
└─────────────────────────────────┴───────┘

# filter nans and certain models

In [57]:
# this will filter all-nan rows
DATA_FILTERED: pl.DataFrame = filter_data(
	DATA_RAW,
	# tinystories and small pythia models look very different in embedding space, so we get rid of them
	# remove_models=["tiny-stories-1M", "pythia-14m"],
)
nan_stats(DATA_FILTERED)

Not removing any models
Removing 14/176 cols
feat.diag.zero_crossing_rate                                 μ=0.00 σ=0.00 x̃=0.00 R=[0.00,0.00] shape=19456 dtype=float64
feat.first_tok.zero_crossing_rate                            μ=0.00 σ=0.00 x̃=0.00 R=[0.00,0.00] shape=19456 dtype=float64
feat.markov_transition.time.zero_crossing_rate               μ=0.00 σ=0.00 x̃=0.00 R=[0.00,0.00] shape=19456 dtype=float64
feat.markov_transition.env.lower.slope                       μ=0.00 σ=0.00 x̃=0.00 R=[-0.00,-0.00] shape=19456 dtype=float64
feat.markov_transition.env.lower.intercept                   μ=0.00 σ=0.00 x̃=0.00 R=[0.00,0.00] shape=19456 dtype=float64
feat.markov_transition.diff.median                           μ=0.00 σ=0.00 x̃=0.00 R=[0.00,0.00] shape=19456 dtype=float64
feat.gram.row.beta_hist.hist.raw.zero_crossing_rate          μ=0.00 σ=0.00 x̃=0.00 R=[0.00,0.00] shape=19456 dtype=float64
feat.gram.col.beta_hist.hist.raw.zero_crossing_rate          μ=0.00 σ=0.00 x̃=0.00 R=[0.00,0.00] shape=19456 dtype=float64
feat.gram.skew.beta_hist.hist.raw.zero_crossing_rate         μ=0.00 σ=0.00 x̃=0.00 R=[0.00,0.00] shape=19456 dtype=float64
feat.log.gram.row.beta_hist.hist.raw.median                  μ=0.00 σ=0.00 x̃=0.00 R=[0.00,0.00] shape=19456 dtype=float64
feat.log.gram.row.beta_hist.hist.raw.zero_crossing_rate      μ=0.00 σ=0.00 x̃=0.00 R=[0.00,0.00] shape=19456 dtype=float64
feat.log.gram.col.beta_hist.hist.raw.median                  μ=0.00 σ=0.00 x̃=0.00 R=[0.00,0.00] shape=19456 dtype=float64
feat.log.gram.col.beta_hist.hist.raw.zero_crossing_rate      μ=0.00 σ=0.00 x̃=0.00 R=[0.00,0.00] shape=19456 dtype=float64
feat.log.gram.skew.beta_hist.hist.raw.zero_crossing_rate     μ=0.00 σ=0.00 x̃=0.00 R=[0.00,0.00] shape=19456 dtype=float64

[ /home/miv/projects/attn/attention-motifs/attention_motifs/features/analysis.py:49 ] remove_cols = ['feat.diag.zero_crossing_rate', 'feat.first_tok.zero_crossing_rate', 'feat.markov_transition.time.zero_crossing_rate', 'feat.markov_transition.env.lower.slope', 'feat.markov_transition.env.lower.intercept', 'feat.markov_transition.diff.median', 'feat.gram.row.beta_hist.hist.raw.zero_crossing_rate', 'feat.gram.col.beta_hist.hist.raw.zero_crossing_rate', 'feat.gram.skew.beta_hist.hist.raw.zero_crossing_rate', 'feat.log.gram.row.beta_hist.hist.raw.median', 'feat.log.gram.row.beta_hist.hist.raw.zero_crossing_rate', 'feat.log.gram.col.beta_hist.hist.raw.median', 'feat.log.gram.col.beta_hist.hist.raw.zero_crossing_rate', 'feat.log.gram.skew.beta_hist.hist.raw.zero_crossing_rate']

shape: (169, 2)
┌─────────────────────────────────┬───────┐
│ feature                         ┆ count │
│ ---                             ┆ ---   │
│ str                             ┆ u32   │
╞═════════════════════════════════╪═══════╡
│ activation.model                ┆ 0     │
│ activation.layer                ┆ 0     │
│ activation.cache_key            ┆ 0     │
│ activation.head                 ┆ 0     │
│ activation.cls                  ┆ 0     │
│ …                               ┆ …     │
│ feat.log.gram.skew.beta_hist.h… ┆ 0     │
│ feat.log.gram.skew.beta_hist.h… ┆ 0     │
│ feat.log.gram.skew.beta_hist.h… ┆ 0     │
│ feat.log.gram.skew.beta_hist.h… ┆ 0     │
│ feat.log.gram.skew.beta_hist.h… ┆ 0     │
└─────────────────────────────────┴───────┘

# scaling

In [58]:
# Pick feature columns
FEATURE_COLS: list[str] = [
	col for col in DATA_FILTERED.columns if col.startswith("feat.")
]

In [59]:
DATA_SCALED: pl.DataFrame = normalize_data(DATA_FILTERED, FEATURE_COLS)
DATA_SCALED

shape: (19_456, 169)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ activatio ┆ activatio ┆ activatio ┆ activatio ┆ … ┆ feat.log. ┆ feat.log. ┆ feat.log. ┆ feat.log │
│ n.model   ┆ n.layer   ┆ n.cache_k ┆ n.head    ┆   ┆ gram.skew ┆ gram.skew ┆ gram.skew ┆ .gram.sk │
│ ---       ┆ ---       ┆ ey        ┆ ---       ┆   ┆ .beta_his ┆ .beta_his ┆ .beta_his ┆ ew.beta_ │
│ str       ┆ i64       ┆ ---       ┆ i64       ┆   ┆ t.h…      ┆ t.h…      ┆ t.h…      ┆ hist.h…  │
│           ┆           ┆ str       ┆           ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ pythia-14 ┆ 0         ┆ blocks.0. ┆ 0         ┆ … ┆ -0.343456 ┆ 0.359227  ┆ -0.344892 ┆ -0.39180 │
│ m         ┆           ┆ attn.hook ┆           ┆   ┆           ┆           ┆           ┆ 7        │
│           ┆           ┆ _pattern  ┆           ┆   ┆           ┆           ┆           ┆          │
│ pythia-14 ┆ 0         ┆ blocks.0. ┆ 1         ┆ … ┆ -0.410395 ┆ 0.156177  ┆ -0.064161 ┆ 0.466565 │
│ m         ┆           ┆ attn.hook ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ _pattern  ┆           ┆   ┆           ┆           ┆           ┆          │
│ pythia-14 ┆ 0         ┆ blocks.0. ┆ 2         ┆ … ┆ -0.274656 ┆ 0.311666  ┆ -0.367625 ┆ -0.23565 │
│ m         ┆           ┆ attn.hook ┆           ┆   ┆           ┆           ┆           ┆ 2        │
│           ┆           ┆ _pattern  ┆           ┆   ┆           ┆           ┆           ┆          │
│ pythia-14 ┆ 0         ┆ blocks.0. ┆ 3         ┆ … ┆ -0.406516 ┆ 0.34822   ┆ -0.321787 ┆ -0.34972 │
│ m         ┆           ┆ attn.hook ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ _pattern  ┆           ┆   ┆           ┆           ┆           ┆          │
│ pythia-14 ┆ 1         ┆ blocks.1. ┆ 0         ┆ … ┆ -0.656743 ┆ -0.035017 ┆ 0.209811  ┆ 1.456192 │
│ m         ┆           ┆ attn.hook ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ _pattern  ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ tiny-stor ┆ 7         ┆ blocks.7. ┆ 11        ┆ … ┆ 0.289547  ┆ -0.446478 ┆ 0.365185  ┆ 0.715034 │
│ ies-1M    ┆           ┆ attn.hook ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ _pattern  ┆           ┆   ┆           ┆           ┆           ┆          │
│ tiny-stor ┆ 7         ┆ blocks.7. ┆ 12        ┆ … ┆ 0.276708  ┆ -0.453319 ┆ 0.367634  ┆ 0.734386 │
│ ies-1M    ┆           ┆ attn.hook ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ _pattern  ┆           ┆   ┆           ┆           ┆           ┆          │
│ tiny-stor ┆ 7         ┆ blocks.7. ┆ 13        ┆ … ┆ 0.257963  ┆ -0.426007 ┆ 0.375109  ┆ 0.649689 │
│ ies-1M    ┆           ┆ attn.hook ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ _pattern  ┆           ┆   ┆           ┆           ┆           ┆          │
│ tiny-stor ┆ 7         ┆ blocks.7. ┆ 14        ┆ … ┆ 0.290326  ┆ -0.474193 ┆ 0.365526  ┆ 0.798103 │
│ ies-1M    ┆           ┆ attn.hook ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ _pattern  ┆           ┆   ┆           ┆           ┆           ┆          │
│ tiny-stor ┆ 7         ┆ blocks.7. ┆ 15        ┆ … ┆ 0.270477  ┆ -0.476585 ┆ 0.369199  ┆ 0.804927 │
│ ies-1M    ┆           ┆ attn.hook ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ _pattern  ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [61]:
nan_stats(DATA_SCALED)

shape: (169, 2)
┌─────────────────────────────────┬───────┐
│ feature                         ┆ count │
│ ---                             ┆ ---   │
│ str                             ┆ u32   │
╞═════════════════════════════════╪═══════╡
│ activation.model                ┆ 0     │
│ activation.layer                ┆ 0     │
│ activation.cache_key            ┆ 0     │
│ activation.head                 ┆ 0     │
│ activation.cls                  ┆ 0     │
│ …                               ┆ …     │
│ feat.log.gram.skew.beta_hist.h… ┆ 0     │
│ feat.log.gram.skew.beta_hist.h… ┆ 0     │
│ feat.log.gram.skew.beta_hist.h… ┆ 0     │
│ feat.log.gram.skew.beta_hist.h… ┆ 0     │
│ feat.log.gram.skew.beta_hist.h… ┆ 0     │
└─────────────────────────────────┴───────┘

# PCA

In [ ]:
# PCA
pca_data: np.ndarray
pca_obj: PCA
pca_data, pca_obj = apply_pca(DATA_SCALED, n_components=10, feature_cols=FEATURE_COLS)

ValueError: Input X contains NaN.
PCA does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [ ]:
# save some data
DATA_SCALED.write_ndjson(Path("../data/features/scaled.jsonl"))
dbg_tensor(pca_data)
np.save("../data/features/pca.npy", pca_data)

# only columns that start with "activation."
# for labelling the PCA plot in the webapp
data_meta: pl.DataFrame = DATA_SCALED[[
	col for col in DATA_SCALED.columns if col.startswith("activation.")
]]
data_meta = data_meta.write_ndjson(Path("../data/features/meta.jsonl"))

In [ ]:
for i in range(1, 3):
	for j in range(0, i):
		plot_embedding(
			pca_data,
			DATA_SCALED["activation.model"],
			(i, j),
			alpha=0.05,
			marker_size=10,
			title=f"2D PCA Embedding ({i}, {j})",
		)